### PR TITLE
Get rid of tcomb dep

### LINKED ISSUE #1: If "font" property doesn't have "font-size" or "font-family" error
using something like this will trough an error
```css
a { font: bold; }
a { font: 12px; }
```
```Error: [parse-css-font] Missing required font-family.```

### PR DESCRIPTION
**Pull request by dy**
This fixes #1, merged with css-list-helpers https://github.com/jedmao/css-list-helpers/pull/1.

Changes:

- removed `coverage` folder (it is in .gitignore anyways)
- added gentle eslint config
- removed `tcomb` dep
- added coverage test

@jedmao please check, that should make the package perfect :)

### CODE REVIEW

**Comment by jedmao** [comment]
Thanks for the effort. I'm going to give this a shot with TypeScript + [io-ts](https://github.com/gcanti/io-ts#the-idea) and see how it goes. Stay tuned!

**Comment by jedmao** [comment]
I'll have this done tonight.

**Comment by dy** [comment]
Ok I would appreciate!
Still wonder why not publishing a minor bump with this PR not to block development (just in case), and then have open time for io-ts experimenting.

**Comment by jedmao** [comment]
@dy there's absolutely no reason to rush a PR, especially when you can just install the version on your branch like so:
```
    "parse-css-font": "https://github.com/dy/parse-css-font.git#master-or-some-other-branch",
```
I do have something against this PR, because I don't feel comfortable merging a PR that goes in a different direction than how I would have done it. We didn't agree to anything up front and that's fine. You have your branch and you can use it until I publish a new version or you can always use your version if you want. That's entirely up to you.

**Comment by jedmao** [comment]
I got too sleepy last night [fixing `css-list-helpers`](https://github.com/jedmao/css-list-helpers/pull/2), a dependency of this package, so I didn't have time to finish this.

**Comment by jedmao** [comment]
See #4

**Comment by jedmao** [comment]
Published fix in version 3.0.0.

**Pull request closed without merging**
